# Generated by Django 3.1.4 on 2020-12-15 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import herp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('A', 'Amphibien'), ('R', 'Reptile')], max_length=1, verbose_name='Ordre')),
                ('scientific_name', models.CharField(max_length=64, verbose_name='Nom scientifique')),
                ('common_name', models.CharField(max_length=64, verbose_name='Nom commun')),
                ('author', models.CharField(max_length=64, verbose_name='Autheur')),
                ('description', models.TextField()),
                ('iucn_status', models.CharField(choices=[('I', 'Données insufissantes'), ('N', 'Non concerné'), ('L', 'Quasi menacé'), ('V', 'Vulnérable'), ('E', 'En danger'), ('C', 'Danger critique'), ('X', 'Eteint')], max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=herp.models.user_directory_path)),
                ('herp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herp.herp')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HerpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=herp.models.herp_directory_path)),
                ('description', models.TextField()),
                ('herp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herp.herp')),
            ],
        ),
    ]
