# Generated by Django 3.1.4 on 2020-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herp',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='herpimage',
            name='image',
            field=models.ImageField(upload_to='uploads/species'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/species/observations/'),
        ),
    ]
