# Generated by Django 3.1.4 on 2020-12-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Population',
            new_name='PopulationSiteReproduction',
        ),
        migrations.AlterModelOptions(
            name='barrier',
            options={'verbose_name': 'Barrière à amphibien', 'verbose_name_plural': 'Barrières à amphibiens'},
        ),
        migrations.AlterModelOptions(
            name='herp',
            options={'verbose_name': 'Espèce', 'verbose_name_plural': 'Espèces'},
        ),
        migrations.AlterModelOptions(
            name='populationsitereproduction',
            options={'verbose_name': 'Population des amphibiens par site', 'verbose_name_plural': 'Populations des amphibiens par site'},
        ),
        migrations.AlterModelOptions(
            name='sitereproduction',
            options={'verbose_name': 'Site de reproduction des amphibiens', 'verbose_name_plural': 'Sites de reproduction des amphibiens'},
        ),
    ]
