# Generated by Django 3.1.4 on 2020-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0002_auto_20201216_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populationsitereproduction',
            options={'verbose_name': 'Population des amphibiens par site de reproduction', 'verbose_name_plural': 'Populations des amphibiens par site de reproduction'},
        ),
        migrations.AddField(
            model_name='barrier',
            name='rte',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
