# Generated by Django 3.1.4 on 2020-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0002_auto_20201215_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='herp',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
