# Generated by Django 3.1.4 on 2020-12-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0003_auto_20201216_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('probabilities', models.CharField(blank=True, choices=[('C', 'Certaine'), ('M', 'Probable'), ('I', 'Impossible')], default='I', max_length=1, null=True)),
                ('population_size', models.CharField(blank=True, choices=[('I', 'Inconnu'), ('P', 'Petite'), ('M', 'Moyenne'), ('G', 'Grande'), ('T', 'Très grande')], default='I', max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='populationsitereproduction',
            name='population_size',
            field=models.CharField(choices=[('I', 'Inconnu'), ('P', 'Petite'), ('M', 'Moyenne'), ('G', 'Grande'), ('T', 'Très grande')], default='I', max_length=1),
        ),
    ]
