# Generated by Django 3.1.4 on 2020-12-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0003_herp_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerpMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='uploads/species')),
                ('description', models.TextField()),
                ('herp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herp.herp')),
            ],
        ),
    ]
