# Generated by Django 3.1.4 on 2020-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0004_herpmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herpimage',
            name='image',
        ),
        migrations.AddField(
            model_name='herpimage',
            name='media',
            field=models.FileField(default='', upload_to='uploads/species'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HerpMedia',
        ),
    ]
