# Generated by Django 3.1.4 on 2020-12-15 14:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0006_herpimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herp',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
