# Generated by Django 3.1.4 on 2020-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0007_auto_20201215_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='details',
        ),
        migrations.AddField(
            model_name='observation',
            name='area',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='quantity',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
