# Generated by Django 3.1.4 on 2020-12-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0008_auto_20201216_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.CharField(choices=[('P', 'Petite'), ('M', 'Moyenne'), ('G', 'Grande'), ('T', 'Très grande')], max_length=1)),
                ('herp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='herp.herp')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=5, verbose_name='Object')),
                ('name', models.CharField(max_length=64, verbose_name="Nom de l'objet")),
                ('commune', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('gps', models.CharField(max_length=64)),
                ('altitude', models.IntegerField()),
                ('surface', models.FloatField()),
                ('slug', models.SlugField()),
                ('population', models.ManyToManyField(through='herp.Population', to='herp.Herp')),
            ],
        ),
        migrations.AddField(
            model_name='population',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='herp.site'),
        ),
    ]
