# Generated by Django 3.1.4 on 2020-12-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herp', '0009_auto_20201216_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
